build-t1:	task01.c
	gcc -Wall task01.c -o task01
build-t2:	task02.c	
	gcc -Wall task02.c -o task02 -lm 
build-t3:	task03.c
	gcc -Wall task03.c -o task03 -lm
run-t1:	task01	
	./task01
run-t2:	task02
	./task02
run-t3:	task03
	./task03
clean:
	rm task01 task02 task03
